### PR TITLE
added storybook for rec table

### LINKED ISSUE #14: Add RecommendationTable component to Storybook (along with fixtures)
- [x] There is a RecommendationsTable.stories.js file in frontend/src/stories/components/Recommendations.
- [x] In the storybook there is an Recommendations Folder with a RecommendationsTable Inside with Empty and Three Recommendations.
- [x] When Empty is clicked there is a table with all of the headers of an Recommendations but with no items in the table.
- [x] When Three Recommendations is clicked there is a table with all of the headers of an recommendation with three items in the table with the correct values corresponding to the values in the recommendationsFixtures.js file.

### PR DESCRIPTION
**Pull request by nick-pellegrin**
closes #14

### CODE REVIEW

**Review by josiahnross — APPROVED** [review]
LGTM

**Review by Gopu2001 — APPROVED** [review]
Everything runs right!

**Comment by csirlin** [comment]
I looked at your storybook and the column "Professor email" is missing values. I think it's because in `recommendationsFixtures.js` it says "preofessorEmail" instead of "professorEmail".

**Review by csirlin — CHANGES_REQUESTED** [review]
I looked at your storybook and the column "Professor email" is missing values. I think it's because in recommendationsFixtures.js it says "preofessorEmail" instead of "professorEmail".

**Review by HarvardWang — APPROVED** [review]
lgtm!

**Review by csirlin — APPROVED** [review]
Looks good now! Thanks for making that change

**Pull request merged**
