### PR TITLE
Josiah - Article Index Placeholder

### LINKED ISSUE #4: Add Placeholder for Article Index Page
- [x] There is a page that shows up when the user goes to `articles/list`
- [x] The page file should be called `ArticlesIndexPage` and should be placed in `frontend/src/main/pages/Articles`
- [x] The page is linked to in `App.js` and can be accessed by logged-in users

### PR DESCRIPTION
**Pull request by josiahnross**
- [x] There is a page that shows up when the user goes to `articles/list`
- [x] The page file should be called `ArticlesIndexPage` and should be placed in `frontend/src/main/pages/Articles`
- [x] The page is linked to in `App.js` and can be accessed by logged-in users

Closes #4

### CODE REVIEW

**Comment by Gopu2001** [comment]
Did you mean a different folder for this task?
- [X] The page file should be called `ArticlesIndexPage` and should be placed in `frontend/pages/articles`

Should `frontend/pages/articles` be `frontend/src/main/pages/articles`?

**Review by HarvardWang — APPROVED** [review]
LGTM!

**Review by Gopu2001 — CHANGES_REQUESTED** [review]
Minor change requested

**Review by Gopu2001 — APPROVED** [review]
LGTM

**Pull request merged**
